// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN22OOA9VDdef3RT8UeGUtKspKyuoHouY',
    appId: '1:33454336954:web:d906996e52c09b256bcb83',
    messagingSenderId: '33454336954',
    projectId: 'chatapp-78454',
    authDomain: 'chatapp-78454.firebaseapp.com',
    storageBucket: 'chatapp-78454.firebasestorage.app',
    measurementId: 'G-F8DZV2PN25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEKd4YwKBKUztkhlaedEPPi1TOPOaBzis',
    appId: '1:33454336954:android:14aa06e89e73d2266bcb83',
    messagingSenderId: '33454336954',
    projectId: 'chatapp-78454',
    storageBucket: 'chatapp-78454.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBc3A5koyO_Fg6HQbJSmAoREGcOg7b6d8',
    appId: '1:33454336954:ios:dc0e8ab60333700f6bcb83',
    messagingSenderId: '33454336954',
    projectId: 'chatapp-78454',
    storageBucket: 'chatapp-78454.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBc3A5koyO_Fg6HQbJSmAoREGcOg7b6d8',
    appId: '1:33454336954:ios:dc0e8ab60333700f6bcb83',
    messagingSenderId: '33454336954',
    projectId: 'chatapp-78454',
    storageBucket: 'chatapp-78454.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN22OOA9VDdef3RT8UeGUtKspKyuoHouY',
    appId: '1:33454336954:web:1e0a72cd530a61e06bcb83',
    messagingSenderId: '33454336954',
    projectId: 'chatapp-78454',
    authDomain: 'chatapp-78454.firebaseapp.com',
    storageBucket: 'chatapp-78454.firebasestorage.app',
    measurementId: 'G-RWHJWDXWLG',
  );
}
